package com.rehab.rehab_center_api.exceptions;

import org.springframework.http.HttpStatus;
import lombok.Getter;

@Getter
public enum ErrorCode {
    USER_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, "USER_ALREADY_EXISTS"),
    EMAIL_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, "EMAIL_ALREADY_EXISTS"),
    ROLE_NOT_FOUND(HttpStatus.BAD_REQUEST, "ROLE_NOT_FOUND"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_NOT_FOUND"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
    ACCESS_DENIED(HttpStatus.FORBIDDEN, "ACCESS_DENIED"),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "VALIDATION_ERROR"),
    POLICE_OFFICER_PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, "POLICE_OFFICER_PROFILE_NOT_FOUND"),
    HANDOVER_SLIP_NOT_FOUND(HttpStatus.NOT_FOUND, "HANDOVER_SLIP_NOT_FOUND"),
    HANDOVER_SLIP_ACCESS_DENIED(HttpStatus.FORBIDDEN, "HANDOVER_SLIP_ACCESS_DENIED"),
    HANDOVER_SLIP_NOT_EDITABLE(HttpStatus.BAD_REQUEST, "HANDOVER_SLIP_NOT_EDITABLE"),
    HANDOVER_SLIP_NOT_SUBMITTABLE(HttpStatus.BAD_REQUEST, "HANDOVER_SLIP_NOT_SUBMITTABLE"),
    HANDOVER_SLIP_NOT_CANCELLABLE(HttpStatus.BAD_REQUEST, "HANDOVER_SLIP_NOT_CANCELLABLE"),
    HANDOVER_SUBJECT_LIST_EMPTY(HttpStatus.BAD_REQUEST, "HANDOVER_SUBJECT_LIST_EMPTY"),
    DUPLICATE_IDENTITY_NUMBER(HttpStatus.CONFLICT, "DUPLICATE_IDENTITY_NUMBER"),
    DUPLICATE_IDENTITY_IN_REQUEST(HttpStatus.BAD_REQUEST, "DUPLICATE_IDENTITY_IN_REQUEST"),
    FILE_REQUIRED(HttpStatus.BAD_REQUEST, "FILE_REQUIRED"),
    INVALID_FILE_TYPE(HttpStatus.BAD_REQUEST, "INVALID_FILE_TYPE"),
    FILE_TOO_LARGE(HttpStatus.BAD_REQUEST, "FILE_TOO_LARGE"),
    FILE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE_UPLOAD_FAILED"),
    STAFF_PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, "STAFF_PROFILE_NOT_FOUND"),
    REHAB_PATIENT_NOT_FOUND(HttpStatus.NOT_FOUND, "REHAB_PATIENT_NOT_FOUND"),
    TREATMENT_PROPOSAL_NOT_FOUND(HttpStatus.NOT_FOUND, "TREATMENT_PROPOSAL_NOT_FOUND"),
    TREATMENT_PROPOSAL_NOT_PENDING(HttpStatus.BAD_REQUEST, "TREATMENT_PROPOSAL_NOT_PENDING"),
    TREATMENT_PROPOSAL_INVALID_TYPE(HttpStatus.BAD_REQUEST, "TREATMENT_PROPOSAL_INVALID_TYPE"),
    TREATMENT_PROPOSAL_STAGE_MISMATCH(HttpStatus.CONFLICT, "TREATMENT_PROPOSAL_STAGE_MISMATCH"),
    TREATMENT_PROPOSAL_INVALID_STAGE_TRANSITION(HttpStatus.BAD_REQUEST, "TREATMENT_PROPOSAL_INVALID_STAGE_TRANSITION"),
    TREATMENT_PROPOSAL_DUPLICATE_PENDING(HttpStatus.CONFLICT, "TREATMENT_PROPOSAL_DUPLICATE_PENDING"),
    CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "CONCURRENT_MODIFICATION"),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_SERVER_ERROR");

    private final HttpStatus httpStatus;
    private final String code;

    ErrorCode(HttpStatus httpStatus, String code) {
        this.httpStatus = httpStatus;
        this.code = code;
    }
}
